# -*- coding: utf-8 -*-
"""Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wgHPZltja1Pe1445SwfX93zqvtwovoAL
"""

from sklearn.linear_model import LinearRegression
LR=LinearRegression()
t=[[5],[6],[7],[8],[9]]
m=[1,2,3,4,5]
LR.fit(t,m)
#LR.predict([[5.5]])

LR.predict([[5.5]])