# -*- coding: utf-8 -*-
"""MATPLOTLIB1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sn3OyDKBGhXsV0WEq3-RfnANuSCNU_Hk
"""

import numpy as np
import matplotlib.pyplot as plt
runs=np.array([100,50,91,78,89,25,34,19,9,10])
w=np.array([1,0,2,0,3,7,8,9,7,5])
plt.scatter(runs,w,color='green')
plt.title('IndvsAus_score')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
tigar=np.linspace(-2*np.pi,2*np.pi,100)
print(tigar)

plt.plot(tigar,np.sin(tigar),color='black')
plt.title("sin(x)")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
#creating x
overs = np.arange(5,50,5)
overs_a = np.arange(5,30,5)
#creating y
runs_i = np.array([25,51,84,131,160,189,220,250,267])
runs_a = np.array([15,41,94,110,151])
wickets = np.array([12,32,96])
#plotting
plt.plot(overs,runs_i,color='blue',label='India')
plt.plot(overs_a,runs_a,color='yellow',label = 'Aus')
#combining two graphs
plt.legend(loc='best')
#displaying the final graph
plt.show()

import matplotlib.pyplot as plt
a = [230,560,780,127,128]
b = [200,160,270,127,400]
years = [1,2,3,4]
profit_a = [(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b = [(b[i]-b[i-1]) for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color='hotpink',linewidth = '7',label = 'CompanyA',marker='>',ms='15',mec='k')
plt.subplot(2,1,1)
plt.plot(years,profit_b,color='black',linestyle='dotted',label = 'CompanyB',marker = 'H')
plt.show()

import numpy as np
a = np.array([25,60,5,10])
labe = ["AIML","Python","Pandas","Numpy"]
colours=['green','yellow','black','red']
plt.pie(a,labels = labe,colors=colours)
plt.show()

#explode
a = np.array([25,60,5,10])
labe = ["AIML","Python","Pandas","Numpy"]
explo = [0.2,0,0,0]
plt.pie(a,labels = labe,explode = explo,startangle = 180)
plt.show()

a = np.array([25,60,5,10])
labe = ["AIML","Python","Pandas","Numpy"]
explo = [0.3,0,0,0]
plt.pie(a,labels = labe,explode = explo,shadow=True)
plt.legend()
plt.show()

a = np.array([25,60,5,10])
labe = ["AIML","Python","Pandas","Numpy"]
color = ['pink','black','coral','yellow']
plt.pie(a,labels = labe,colors= color)
plt.legend()
plt.show()