# -*- coding: utf-8 -*-
"""NUMPY1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rldtYyvaQRAyKrpMhvtVuKnLeJOvd2eb
"""

import numpy as np
#Creating arrays
arr=np.array(([1, 2, 3, 4, 5]),dtype=float)
print(arr)

import numpy as np
zeroarr=np.zeros((3, 3),dtype=int)
print(zeroarr)
onesarr=np.ones((2, 2),dtype=int)
arrangearr=np.arange(10)
print(arrangearr)

import numpy as np
#Array Manipulation
arr=np.array([1, 2, 3, 4, 5])
reshape=arr.reshape(5, 1)
print(reshape)
sliced=arr[2:4]
print(sliced)

import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
d=np.linalg.eig(c)
print(d)

import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
b=a. T
print(b)
b=np.split(a,4)
print(b)

import numpy as np
data=np.loadtxt("/content/DATASET/dap.txt",dtype=int)
d=np.savetxt("/content/dap.txt",data)
print(d)
print(data)

import numpy as np
a=np.arange(0,100,5)
print(a)
da=np.savetxt("/content/varshu.txt",a)

import numpy as np
a=np.random.rand()
print(a)
b=np.random.randint(2,10)
print(b)

import numpy as np
ar=np.array([[1,2],[4,5]])
print(type(ar))
print(ar.ndim)
print(ar.shape)

import numpy as np
a=np.linspace(0.8,2,5)
print(a)

import numpy as np
c=np.arange(24)
print(c)
print(c.reshape(2,3,4))

import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a*b)
print(a@b)
print(np.dot(a,b))
print(a+b)

from numpy import random
a=np.ones((2,3),dtype=int)
c=np.random.random((2,2))
print(a)
print(a.sum())
print(a.sum(axis=1))
print(a.sum(axis=0))
p=np.floor(np.random.random((2,2)))
q=np.ceil(np.random.random((2,2)))
print(c)
print(p)
print(q)

from numpy import random
a=np.ones((2,3),dtype=int)
print(a)
print(a.max())
print(a.max(axis=1))
print(a.max(axis=0))

from numpy import random
a=np.array([[1,2],[3,4]])
print(a)
print(a.min())
print(a.min(axis=1))
print(a.min(axis=0))

from numpy import random
a=np.array([[1,2],[3,4]])
print(a)
print(a.cumsum())
print(a.cumsum(axis=1))
print(a.cumsum(axis=0))

from numpy import random
a=np.array([2,3,5,6])
print(a.cumsum())

from numpy import random
g=np.array([2, 3, 5, 6, 7, 8])
g.resize(3,2)
print(g)
print(g.shape)

from numpy import random
r=np.array([2, 3, 5, 6, 7, 8])
e=np.array([1, 2, 3, 4, 5, 6])
r.resize(2,3)
e.resize(2,3)
print(np.vstack((r,e)))
print(np.hstack((r,e)))

import numpy as np
a=np.arange(30).reshape(2,3,5)
print(a)
print(np.dstack(a))

"""number of rows became number of groups,
columns became rows,
group became columns.
"""

import numpy as np
a1=np.eye(4)
print(a1)

import numpy as np
a=np.full((2,2),3)
print(a)
print(a.itemsize)

import numpy as np
x=[1,2,3]
a=np.asarray(x)
print(a)
print(type(a))

import numpy as np
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

"""inner:element wise multipication and then sum,
outer:first arrays elements are multiplied with all elements in 2nd array,cross:cross multiplication
"""

import numpy as np
a=np.array([1.1,2.2,3.4,4.4,5.5,6.6,7.7])
b=np.rint(a)
print(b)

import numpy as np
x=np.array([1,2,3,4,5])
y=np.array([2,7,8,9,10])
c=np.true_divide(x,y)
print(c)

import numpy as np
a=np.array([1,1,2,4,3,5,3])
b=np.unique(a)
print(b)

import numpy as np
a=np.array([[1,2,3,4],[1,2,3,4]])
b=np.array([[5,6,7,8],[5,6,7,8]])
c=np.union1d(a,b)
print(c)

import numpy as np
a=np.array([[1,2,3,4],[1,2,3,4]])
b=np.array([[5,3,7,8],[5,6,4,8]])
c=np.intersect1d(a,b)
print(c)

import numpy as np
a=np.array([[1,2,3,4],[1,2,11,4]])
b=np.array([[5,6,3,8],[5,6,7,8]])
c=np.setdiff1d(a,b)
print(c)

import numpy as np
a=8
b=6
c=np.hypot(a,b)
print(c)

x=np.sin(0)
print(x)

a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,25,25,30])
c=np.divmod(a,b)
print(c)

a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,25,25,30])
c=np.mod(a,b)
print(c)

a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,25,25,30])
c=np.divide(a,b)
print(c)

a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,25,25,30])
c=np.multiply(a,b)
print(c)

a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,25,25,30])
c=np.matmul(a,b)
print(c)

from numpy import random
x=random.normal(size=(2,3))
print(x)

x=random.normal(loc=1,scale=2,size=(2,3))
print(x)

"""loc:mean value,scale:standard deviation"""

x=random.binomial(n=12,p=0.5,size=10)
print(x)

"""p=probability,n=trails"""

x=random.poisson(lam=2,size=10)
print(x)

x=random.choice([1,2,3,4])
print(x)

x=random.choice([3,5],p=(0.5,0.5),size=(3,5))
print(x)

import numpy as np
import matplotlib.pyplot as plt
runs=np.array([100,50,91,78,89,25,34,19,9,10])
w=np.array([1,0,2,0,3,7,8,9,7,5])
plt.scatter(runs,w,color='green')
plt.title('IndvsAus_score')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
tigar=np.linspace(-2*np.pi,2*np.pi,100)
print(tigar)

plt.plot(tigar,np.sin(tigar),color='black')
plt.title("sin(x)")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
#creating x
overs = np.arange(5,50,5)
overs_a = np.arange(5,30,5)
#creating y
runs_i = np.array([25,51,84,131,160,189,220,250,267])
runs_a = np.array([15,41,94,110,151])
wickets = np.array([12,32,96])
#plotting
plt.plot(overs,runs_i,color='blue',label='India')
plt.plot(overs_a,runs_a,color='yellow',label = 'Aus')
#combining two graphs
plt.legend(loc='best')
#displaying the final graph
plt.show()

import matplotlib.pyplot as plt
a = [230,560,780,127,128]
b = [200,160,270,127,400]
years = [1,2,3,4]
profit_a = [(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b = [(b[i]-b[i-1]) for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color='hotpink',linewidth = '7',label = 'CompanyA',marker='>',ms='15',mec='k')
plt.subplot(2,1,1)
plt.plot(years,profit_b,color='black',linestyle='dotted',label = 'CompanyB',marker = 'H')
plt.show()

a = np.array([25,60,5,10])
labe = ["AIML","Python","Pandas","Numpy"]
colours=['green','yellow','black','red']
plt.pie(a,labels = labe,colors=colours)
plt.show()

#explode
a = np.array([25,60,5,10])
labe = ["AIML","Python","Pandas","Numpy"]
explo = [0.2,0,0,0]
plt.pie(a,labels = labe,explode = explo,startangle = 180)
plt.show()

a = np.array([25,60,5,10])
labe = ["AIML","Python","Pandas","Numpy"]
explo = [0.3,0,0,0]
plt.pie(a,labels = labe,explode = explo,shadow=True)
plt.legend()
plt.show()

a = np.array([25,60,5,10])
labe = ["AIML","Python","Pandas","Numpy"]
color = ['pink','black','coral','yellow']
plt.pie(a,labels = labe,colors= color)
plt.legend()
plt.show()