# -*- coding: utf-8 -*-
"""TIMESERIES ANALYSIS(PD).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qp8yW-c3-XI-u1iurrRctvVfSMsmiS1A
"""

import pandas as pd
data={'date': pd.date_range(start='2024-02-01', end='2024-02-10'),
      'sales': [10, 15, 12, 18, 20, 25, 22, 28, 30, 35]}
df=pd.DataFrame(data)
df.set_index('date',inplace=True)

rolling_avg=df.rolling(window=3).mean()
print(rolling_avg)

import pandas as pd
data={'date': pd.date_range(start='2024-03-01', end='2024-03-31',freq='D'),
      'sales': [10, 15, 12, 18, 20, 25, 22, 28, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140]}
df=pd.DataFrame(data)
df.set_index('date',inplace=True)
monthly_mean=df.resample('M').mean()
print(monthly_mean)

import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('/content/drive/MyDrive/DATASET/demand_june.csv',parse_dates=['date'], index_col='date')

print(df.head())
print(df.describe())
df.plot()
plt.xlabel('Date')
plt.ylabel('Value')
plt.title('Time Series Data')
plt.show()

subset=df['2023-01-01':'2023-12-31']
print(subset)
subset=df['2023']
subset=df['2023-01']

monthly_mean=df.resample('M').mean()
print(monthly_mean)

rolling_avg=df.rolling(window=30).mean()
print(rolling_avg)

shifted_forward=df.shift(1)
print(shifted_forward)
shifted_backward=df.shift(-1)
print(shifted_backward)

df=df.tz_localize('UTC')
print(df)
df=df.tz_convert('US/Eastern')
print(df)

import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('/content/drive/MyDrive/DATASET/demand_june.csv',parse_dates=['date'], index_col='date' )